# Dockerfile to build the dev branch of FreeSurfer
# Based on Ubuntu 16.04.3 LTS (Xenial Xerus)
FROM ubuntu:xenial

RUN apt-get update && \
    apt-get install -y \
      automake \
      bc \
      build-essential \
      g++-4.8 \
      gcc-4.8 \
      gfortran \
      git \
      libfreetype6-dev \
      libgfortran-4.8-dev \
      libglu1-mesa-dev \
      libjpeg62-dev \
      libtool-bin \
      libtool \
      libxmu-dev \
      libxmu-headers \
      libxi-dev \
      libx11-dev \
      libxml2-utils \
      libxt-dev \
      libxaw7-dev \
      liblapack-dev \
      libgomp1 \
      libxmu6 \
      libxt6 \
      perl \
      sudo \
      tcsh \
      uuid-dev \
      vim-common \
      wget

# Install cmake 3.12
WORKDIR /tmp/cmake
RUN wget http://www.cmake.org/files/v3.12/cmake-3.12.0.tar.gz && tar xf cmake-3.12.0.tar.gz && cd cmake-3.12.0 && ./configure && make && make install

RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50 && \
    update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50
